---
# file: rename_headnode.yml
- hosts: headnode
  vars_files:
    - [ "group_vars/all_local", "group_vars/all" ]
    - roles/gridengine_master/defaults/main.yml
    
  tasks:      
    - name: Restart primary network interface
      shell: bash -lc "ifdown {{ ansible_default_ipv4.alias }} && ifup {{ ansible_default_ipv4.alias }}"
      when: "ansible_default_ipv4.alias is defined"
      register: output
    - debug: var=output.stderr

    - name: Execute the gridengine-master playbook
      include: roles/gridengine_master/tasks/main.yml

    - name: Restart celeryd processes
      service: name=celeryd state=restarted

    - name: restart ionJobServer
      service: name=ionJobServer state=restarted

    - name: restart ionPlugin
      service: name=ionPlugin state=restarted

    - name: Regenerate self-signed SSL cert with current hostname
      shell: /usr/sbin/make-ssl-cert generate-default-snakeoil --force-overwrite
      ignore_errors: True

    #-----------------------------------------------------------------------------
    # Update the tsconf.log file
    #-----------------------------------------------------------------------------
    - name: Get version of ion-tsconfig
      shell: dpkg -l ion-tsconfig | tail -1 | awk '{print $3}'
      register: tsconfig_version
  
    - name: Create/Update tsconf.log
      template: src=templates/tsconf.conf.j2 dest=/etc/torrentserver/tsconf.conf mode=0644 owner=root group=root

# If there are compute nodes, they need to reconfigure themselves
- hosts: iontorrent_computes
  tasks:
    # Set host location of Ion Torrent Server Daemons
    #function config_cluster_settings()
    - name: Update cluster configuration file - cluster_settings.py
      lineinfile: dest={{ tsconfig_dir }}/local_cluster_settings.py
                    state=present
                    create=yes
                    owner=ionadmin group=ionadmin mode=0644
                    regexp="^{{ item }}.*"
                    line="{{ item }} = '{{ groups.headnode[0] }}'"
      with_items:
        - PLUGINSERVER_HOST
        - JOBSERVER_HOST
        - CRAWLER_HOST

# gridengine-exec on compute nodes needs to be shutdown and reconfigured for the new hostname
- hosts: gridengine_clients
  vars_files:
    - [ "group_vars/all_local", "group_vars/all" ]
    - roles/gridengine_clients/defaults/main.yml
  tasks:
    - name: Shutdown gridengine-exec on compute node
      service: name=gridengine-exec state=stopped
    - name: Edit act_qmaster file on compute node
      shell: bash -lc "echo {{ groups.headnode[0] }} > /var/lib/gridengine/iontorrent/common/act_qmaster"
    - name: Execute the gridengine-clients playbook
      include: roles/gridengine_clients/tasks/main.yml

# TODO
# If headnode's /results is being exported to compute nodes, the mount instructions need updating.
#- hosts: computes
#  roles:
#    nfs_clients
