---
# file: software_update.yml
- hosts: iontorrent_master
  vars_files:
    - [ "group_vars/all_local", "group_vars/all" ]
  tasks:
    - name:
      include: globals.yml

    # Ensure Ion system daemons are stopped
    - name: Ion Daemons shutting down...
      service: name={{ item }} state=stopped
      with_items:
        - ionCrawler
        - ionJobServer
        - ionPlugin
        - celerybeat
        - celeryd
      ignore_errors: Yes

    # Replace official ubuntu repo with Ion-sourced ubuntu repo
    - name: Disable /etc/apt/sources.list
      template: src=templates/sources.list.j2
                dest=/etc/apt/sources.list{{ FUNKYEXT|default('') }}
                owner=root group=root mode=644

    - name: Add /etc/apt/sources.list.d/iontorrent-ubuntu.list
      template: src=templates/iontorrent-ubuntu.j2
                dest=/etc/apt/sources.list.d/iontorrent-ubuntu.list{{ FUNKYEXT|default('') }}
                owner=root group=root mode=644

    # Adding IonReporter plugin repository
    - name: Add /etc/apt/sources.list.d/ionreporter-plugin.list
      template: src=templates/ionreporter-plugin.j2
                dest=/etc/apt/sources.list.d/ionreporter-plugin.list{{ FUNKYEXT|default('') }}
                owner=root group=root mode=644

    - name:
      apt: update_cache=yes

    - name: apt-get autoclean
      shell: bash -c 'apt-get autoclean'

    - name: Set tmpreaper package preseed values
      script: '{{ ansible_env.PWD }}/roles/common/files/tmpreaper.preseed'

    - name: Set grub-pc package preseed values
      script: 'files/grub-pc.preseed \"{{ GRUB_BOOT_DEVICE }}\" '
      when: GRUB_BOOT_DEVICE is defined

    # Make a backup of the postgres database.  Pkg ion-dbreports typically makes
    # schema changes during installation so we want a backup.
    - name: Backup postgres database
      script: files/postgres_bckup.sh

    # Install or Update all packages listed
    - name: Install common system packages
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ common_syspkg_list }}"
      when: item != ''
    - name: Install system packages for head node
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ ionmaster_syspkg_list }}"
      when: item != ''
    - name: Install Ion packages for head node
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ ionmaster_ionpkg_list }}"
      when: item != ''
    - name: Install 3rd party plugin packages
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ ionmaster_pluginpkg_list }}"
      when: item != ''
      ignore_errors: yes

    # Packages to remove from system
    # this step needs to be after ion-dbreports>=5.2.x install
    # samtools is required by ion-dbreports<5.2
    - name: Packages Removal Process
      apt: name={{ item }} state=absent
      with_items:
        - samtools

    # Updates all installed packages.
    - name: Install any available updates
      shell: bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade'
      register: debug
      when: UPDATE_SYSTEM|default(True)

    - debug: var=debug.stdout_lines

    - name: configuration error fixing.
      include: fixes.yml

    # Ensure Ion system daemons are started
    - name: Ion Daemons starting up...
      service: name={{ item }} state=started
      with_items:
        - celeryd
        - celerybeat
        - ionCrawler
        - ionJobServer
        - ionPlugin
      ignore_errors: Yes

    #-----------------------------------------------------------------------------
    # Create/update the tsconf.log file
    #-----------------------------------------------------------------------------
    - name: Get version of ion-tsconfig
      shell: dpkg -l ion-tsconfig | tail -1 | awk '{print $3}'
      register: tsconfig_version

    - name: Create/Update tsconf.log
      template: src=templates/tsconf.conf.j2 dest=/etc/torrentserver/tsconf.conf mode=0644 owner=root group=root

- hosts: iontorrent_computes
  tasks:
    #-----------------------------------------------------------------------------
    # On each compute node, we need to replicate the Ion Repository configured
    # on the head node.
    #-----------------------------------------------------------------------------

    # Replace sources.list with empty file
    - name: Disable /etc/apt/sources.list
      template: src=templates/sources.list.j2
                dest=/etc/apt/sources.list{{ FUNKYEXT|default('') }}
                owner=root group=root mode=644

    - name: Purge compute node's /etc/apt/sources.list.d directory
      shell: bash -lc "rm -f /etc/apt/sources.list.d/*"

    - name: Replicating head node's /etc/apt/source.list.d/
      copy: src={{ item }} dest=/etc/apt/sources.list.d/ mode=0644
      with_fileglob:
        - /etc/apt/sources.list.d/*

    - name:
      apt: update_cache=yes

    - name: apt-get autoclean
      shell: bash -c 'apt-get autoclean'

    # Install or Update all packages listed
    - name: Install common system packages
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ common_syspkg_list }}"
      when: item != ''
    - name: Install system packages for compute resource - apt
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ ioncompute_syspkg_list }}"
      when: item != ''
    - name: Install Ion packages for compute resource - apt
      apt: name={{ item }} state=latest force=yes
      with_items: "{{ ioncompute_ionpkg_list }}"
      when: item != ''

    # Packages to remove from system
    - name: Packages Removal Process
      apt: name={{ item }} state=absent
      with_items:
        - samtools

    # Install all available updates to installed packages
    - name: Install any available updates
      shell: bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy upgrade'
      register: debug
      when: UPDATE_SYSTEM|default(True)

    - debug: var=debug.stdout_lines

    - include: roles/iontorrent_computes/tasks/software_update.yml
